import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'


export default function Home() {
  const [users, setUsers] = useState([])

  useEffect(() => {
    fetch("https://randomuser.me/api/?results=100")
    .then((res) => res.json())
    .then((data) => {
      setUsers(data)
    })
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
      {!users? <p> No users found </p>: users.results?.map( user => (
        <div key ={user.id.name} class="card w-25 text-bg-light mb-2">
          <div class="card-body">
            <img src={user.picture.medium} class="card-img-left"></img>
            <h5 class="card-title" >{user.name.first} {user.name.last}</h5>
            <p class="card-text"> {user.location.country}</p>
          </div>
        </div>
      ))}
      </main>

      <footer className={styles.footer}>
        <a href='https://github.com/Kayots/crud'> TEAM ANC </a>
      </footer>
    </div>
  )
}
